"""构建数据清单 output/manifest.csv。

扫描 result/（R1）与 reader_2_result/（R2），逐例解析图像与掩膜 NRRD，
输出影像号、路径、序列名、几何信息、标签统计、双读者对齐信息及标签语义。
R1 标签固定为 1=肿瘤、2=脂肪、3=肌肉；R2 仅在标签 2/3 同时存在时以
同图内平均灰度较低者判为肌肉，单标签病例标记为未解析。几何校验：图像与掩膜
在容差 atol=1e-3 内一致，兼容 3D Slicer 导出浮点舍入。
"""
from __future__ import annotations

import argparse
import math
import os
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import SimpleITK as sitk

from workflow_utils import atomic_write_csv, physical_points_inside_image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(ROOT)
ASCII_PROJECT_ROOT = os.path.join(os.path.dirname(PROJECT_ROOT), "radiomics26")
DIR_R1 = os.path.join(ROOT, "result")
DIR_R2 = os.path.join(ROOT, "reader_2_result")
OUT_DIR = os.path.join(ROOT, "output")
MANIFEST_CSV = os.path.join(OUT_DIR, "manifest.csv")
ROI_XLSX = os.path.join(ROOT, "ROI_list.xlsx")
QC_REPORT = os.path.join(OUT_DIR, "qc", "qc_report.csv")

TOL = 1e-3


def ascii_path(path: str) -> str:
    """Route local Windows SimpleITK reads through the ASCII junction."""
    absolute = os.path.abspath(str(path))
    project_root = os.path.abspath(PROJECT_ROOT)
    if absolute.lower().startswith((project_root + os.sep).lower()):
        return os.path.join(
            ASCII_PROJECT_ROOT, absolute[len(project_root) + 1:])
    return absolute
MIN_TUMOR_VOXELS = 10


def resolve_r2_muscle_label(label2_mean: float, label3_mean: float
                             ) -> Tuple[str, str, str]:
    """Resolve the R2 muscle label without guessing.

    R2 may use either label 2 or label 3 for muscle.  A decision is valid
    only when both labels are present and their means are finite and unequal;
    the lower mean is muscle.  The returned tuple is ``(label, status,
    failure_code)``.
    """
    has2 = math.isfinite(label2_mean)
    has3 = math.isfinite(label3_mean)
    if has2 and has3:
        if label2_mean < label3_mean:
            return "2", "resolved", ""
        if label3_mean < label2_mean:
            return "3", "resolved", ""
        return "", "unresolved", "R2_MUSCLE_LABEL_UNRESOLVED"
    if has2 or has3:
        return "", "unresolved", "R2_MUSCLE_LABEL_UNRESOLVED"
    return "", "missing", "R2_MUSCLE_LABEL_MISSING"


def is_label_file(name: str) -> bool:
    return "label" in name.lower()


def nrrd_files(d: str) -> Tuple[List[str], List[str]]:
    files = sorted(f for f in os.listdir(d) if f.lower().endswith(".nrrd"))
    labels = [f for f in files if is_label_file(f)]
    images = [f for f in files if not is_label_file(f)]
    return images, labels


def geometry(img: sitk.Image) -> dict:
    return {"sizes": list(img.GetSize()), "spacing": list(img.GetSpacing()),
            "origin": list(img.GetOrigin()), "direction": list(img.GetDirection())}


def geom_diff(a: dict, b: dict) -> float:
    return max(abs(x - y)
               for k in ("spacing", "origin", "direction")
               for x, y in zip(a[k], b[k]))


def direction_diff(a: dict, b: dict) -> float:
    return max(abs(x - y) for x, y in zip(a["direction"], b["direction"]))


def fov_covers(image: sitk.Image, pts: np.ndarray) -> bool:
    """用物理点到连续索引的变换判断倾斜图像是否覆盖全部点。"""
    return physical_points_inside_image(image, pts)


def tumor_bbox_corners(mask_arr: np.ndarray, geom: dict) -> Optional[np.ndarray]:
    """掩膜中肿瘤（标签1）包围盒的 8 个物理角点。"""
    zs, ys, xs = np.where(mask_arr == 1)
    if len(zs) == 0:
        return None
    idx = np.array([[x, y, z] for z in (zs.min(), zs.max())
                    for y in (ys.min(), ys.max())
                    for x in (xs.min(), xs.max())], float)
    d = np.array(geom["direction"]).reshape(3, 3)
    sp = np.array(geom["spacing"])
    o = np.array(geom["origin"])
    return o + (d @ (sp[:, None] * idx.T)).T


def save_qc(new_rows: List[Dict]) -> None:
    rows = []
    if os.path.exists(QC_REPORT):
        try:
            rows = pd.read_csv(QC_REPORT, dtype=str).to_dict("records")
        except Exception:
            rows = []
    # The manifest stage is a complete rebuild.  Remove its previous records
    # so that a corrected source directory cannot leave stale FILE_COUNT or
    # geometry errors in the consolidated QC report.  Preserve QC records
    # generated by downstream stages.
    rows = [r for r in rows if str(r.get("阶段", "")) != "manifest"]
    rows.extend(new_rows)
    atomic_write_csv(pd.DataFrame(rows), QC_REPORT)


def main() -> None:
    ap = argparse.ArgumentParser(description="构建数据清单 manifest.csv")
    ap.add_argument("--manifest", default=MANIFEST_CSV)
    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.manifest), exist_ok=True)

    ids = sorted(d for d in os.listdir(DIR_R1) if os.path.isdir(os.path.join(DIR_R1, d)))
    r2_ids = {d for d in os.listdir(DIR_R2) if os.path.isdir(os.path.join(DIR_R2, d))}
    rows: List[Dict] = []
    qc_rows: List[Dict] = []

    for pid in ids:
        d1 = os.path.join(DIR_R1, pid)
        img1, lbl1 = nrrd_files(d1)
        row = {"影像号": pid, "图像文件": "", "掩膜文件": "", "序列名": "",
               "尺寸": "", "层厚mm": "", "面内间距mm": "", "原点": "", "方向矩阵": "",
               "标签集合": "", "肿瘤体素": "", "肿瘤体积mm3": "", "肌肉体素": "",
               "脂肪体素": "", "几何一致": "1", "是否双读者": "0",
               "R2图像文件": "", "R2掩膜文件": "", "R2方向差异": "", "R2覆盖R1肿瘤": "",
               "R1标签2均灰度": "", "R1标签3均灰度": "",
               "R2标签2均灰度": "", "R2标签3均灰度": "",
               "R2肌肉标签": "", "R2肌肉标签状态": "",
               "R2肿瘤体素": "", "排除": "0", "排除原因": ""}
        if len(img1) != 1 or len(lbl1) != 1:
            qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "ERROR",
                            "代码": "FILE_COUNT", "说明": f"R1 图像{len(img1)}个/掩膜{len(lbl1)}个"})
            row.update({"排除": "1", "排除原因": "文件解析失败"})
            rows.append(row)
            continue
        row["图像文件"] = os.path.relpath(os.path.join(d1, img1[0]), ROOT)
        row["掩膜文件"] = os.path.relpath(os.path.join(d1, lbl1[0]), ROOT)
        row["序列名"] = os.path.splitext(img1[0])[0]
        i1 = sitk.ReadImage(ascii_path(os.path.join(d1, img1[0])))
        m1 = sitk.ReadImage(ascii_path(os.path.join(d1, lbl1[0])))
        g1 = geometry(i1)
        a1 = sitk.GetArrayFromImage(m1)
        cnt = np.bincount(a1.ravel(), minlength=4)
        tumor1, fat1, muscle1 = int(cnt[1]), int(cnt[2]), int(cnt[3])
        ai1 = sitk.GetArrayFromImage(i1)
        l2_1 = float(ai1[a1 == 2].mean()) if fat1 > 0 else float("nan")
        l3_1 = float(ai1[a1 == 3].mean()) if muscle1 > 0 else float("nan")
        g_ok = g1["sizes"] == geometry(m1)["sizes"] and geom_diff(g1, geometry(m1)) <= TOL
        if not g_ok:
            qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "WARN",
                            "代码": "GEOM_MISMATCH", "说明": "图像与掩膜几何超出容差"})
        row.update({
            "尺寸": "x".join(map(str, g1["sizes"])),
            "层厚mm": f"{g1['spacing'][2]:.4f}",
            "面内间距mm": f"{g1['spacing'][0]:.4f}",
            "原点": " ".join(f"{x:.4f}" for x in g1["origin"]),
            "方向矩阵": " ".join(f"{x:.6f}" for x in g1["direction"]),
            "标签集合": "{" + ",".join(map(str, sorted(set(a1.ravel().tolist())))) + "}",
            "肿瘤体素": tumor1,
            "肿瘤体积mm3": round(tumor1 * float(np.prod(g1["spacing"])), 2),
            "肌肉体素": muscle1,
            "脂肪体素": fat1,
            "R1标签2均灰度": f"{l2_1:.2f}" if not math.isnan(l2_1) else "",
            "R1标签3均灰度": f"{l3_1:.2f}" if not math.isnan(l3_1) else "",
            "几何一致": "1" if g_ok else "0",
        })
        if tumor1 == 0:
            row.update({"排除": "1", "排除原因": "无肿瘤勾画"})
        elif tumor1 < MIN_TUMOR_VOXELS:
            row["排除原因"] = "肿瘤体素<10（记录评估）"

        if pid in r2_ids:
            row["是否双读者"] = "1"
            d2 = os.path.join(DIR_R2, pid)
            img2, lbl2 = nrrd_files(d2)
            if len(img2) != 1 or len(lbl2) != 1:
                qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "ERROR",
                                "代码": "FILE_COUNT", "说明": f"R2 图像{len(img2)}个/掩膜{len(lbl2)}个"})
            else:
                row["R2图像文件"] = os.path.relpath(os.path.join(d2, img2[0]), ROOT)
                row["R2掩膜文件"] = os.path.relpath(os.path.join(d2, lbl2[0]), ROOT)
                i2 = sitk.ReadImage(ascii_path(os.path.join(d2, img2[0])))
                m2 = sitk.ReadImage(ascii_path(os.path.join(d2, lbl2[0])))
                g2 = geometry(i2)
                a2 = sitk.GetArrayFromImage(m2)
                cnt2 = np.bincount(a2.ravel(), minlength=4)
                row["R2肿瘤体素"] = int(cnt2[1])
                row["R2方向差异"] = "1" if direction_diff(g1, g2) > TOL else "0"
                pts = tumor_bbox_corners(a1, g1)
                row["R2覆盖R1肿瘤"] = "1" if (pts is not None and fov_covers(i2, pts)) else "0"
                # R2 肌肉/脂肪判别：同图内标签2与标签3平均灰度，较低者为肌肉
                ai2 = sitk.GetArrayFromImage(i2)
                l2_2 = float(ai2[a2 == 2].mean()) if cnt2[2] > 0 else float("nan")
                l3_2 = float(ai2[a2 == 3].mean()) if cnt2[3] > 0 else float("nan")
                row["R2标签2均灰度"] = f"{l2_2:.2f}" if not math.isnan(l2_2) else ""
                row["R2标签3均灰度"] = f"{l3_2:.2f}" if not math.isnan(l3_2) else ""
                muscle_label, label_status, failure_code = resolve_r2_muscle_label(
                    l2_2, l3_2)
                row["R2肌肉标签"] = muscle_label
                row["R2肌肉标签状态"] = label_status
                if failure_code:
                    qc_rows.append({
                        "影像号": pid, "阶段": "manifest", "级别": "ERROR",
                        "代码": failure_code,
                        "说明": (
                            "R2 标签2/3平均灰度相同，无法解析肌肉标签；跳过R2"
                            if (math.isfinite(l2_2) and math.isfinite(l3_2))
                            else "R2 标签2/3仅存在一个，无法解析肌肉标签；跳过R2"
                            if failure_code == "R2_MUSCLE_LABEL_UNRESOLVED"
                            else "R2 标签2/3均不存在；跳过R2"
                        ),
                    })
        rows.append(row)

    df = pd.DataFrame(rows)
    atomic_write_csv(df, args.manifest)
    save_qc(qc_rows)

    roi = pd.read_excel(ROI_XLSX)
    col = "影像号" if "影像号" in roi.columns else roi.columns[0]
    roi_ids = set(str(x).strip() for x in roi[col])
    id_set = set(ids)
    n_excl = int((df["排除"] == "1").sum())
    n_small = int(df["排除原因"].str.contains("体素<10", na=False).sum())
    n_pair = int((df["是否双读者"] == "1").sum())
    d2 = df.loc[df["是否双读者"] == "1"]
    r2s = d2["R2肌肉标签状态"].value_counts().to_dict()
    r2ml = d2["R2肌肉标签"].value_counts().to_dict()
    n_align = int((d2["R2方向差异"] == "1").sum())
    n_cover = int((d2["R2覆盖R1肿瘤"] == "1").sum())

    print(f"R1 病例数: {len(ids)} (result 内重复: {len(ids) - len(id_set)})")
    print(f"ROI_list 行数: {len(roi)}, 重复影像号: {int(roi[col].astype(str).str.strip().duplicated().sum())}, "
          f"与 result 交集: {len(id_set & roi_ids)}")
    print(f"ROI_list 有而 result 无: {sorted(roi_ids - id_set)[:10]}")
    print(f"result 有而 ROI_list 无: {sorted(id_set - roi_ids)[:10]}")
    print(f"排除(无肿瘤勾画): {n_excl}, 肿瘤<10体素(记录评估): {n_small}")
    print(f"双读者病例: {n_pair}, R2方向差异: {n_align}, R2覆盖R1肿瘤: {n_cover}")
    print(f"R2 肌肉标签状态: {r2s}")
    print(f"R2 肌肉标签: {r2ml}")
    print(f"清单已写入: {args.manifest}")


if __name__ == "__main__":
    main()
