"""构建数据清单 output/manifest.csv。

扫描 result/（R1）与 reader_2_result/（R2），逐例解析图像与掩膜 NRRD，
输出影像号、路径、序列名、几何信息、标签统计、双读者对齐信息及
标签 2/3 肌肉判别（同图内平均灰度较低者为肌肉）。几何校验：图像与掩膜
在容差 atol=1e-3 内一致，兼容 3D Slicer 导出浮点舍入。
"""
from __future__ import annotations

import argparse
import math
import os

import numpy as np
import pandas as pd
import SimpleITK as sitk

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR_R1 = os.path.join(ROOT, "result")
DIR_R2 = os.path.join(ROOT, "reader_2_result")
OUT_DIR = os.path.join(ROOT, "output")
MANIFEST_CSV = os.path.join(OUT_DIR, "manifest.csv")
ROI_XLSX = os.path.join(ROOT, "ROI_list.xlsx")
QC_REPORT = os.path.join(OUT_DIR, "qc", "qc_report.csv")

TOL = 1e-3
MIN_TUMOR_VOXELS = 10


def is_label_file(name: str) -> bool:
    return "label" in name.lower()


def nrrd_files(d: str) -> tuple[list[str], list[str]]:
    files = sorted(f for f in os.listdir(d) if f.lower().endswith(".nrrd"))
    labels = [f for f in files if is_label_file(f)]
    images = [f for f in files if not is_label_file(f)]
    return images, labels


def geometry(img: sitk.Image) -> dict:
    return {"sizes": list(img.GetSize()), "spacing": list(img.GetSpacing()),
            "origin": list(img.GetOrigin()), "direction": list(img.GetDirection())}


def geom_diff(a: dict, b: dict) -> float:
    return max(abs(x - y)
               for k in ("spacing", "origin", "direction")
               for x, y in zip(a[k], b[k]))


def direction_diff(a: dict, b: dict) -> float:
    return max(abs(x - y) for x, y in zip(a["direction"], b["direction"]))


def fov_covers(img_geom: dict, pts: np.ndarray) -> bool:
    """img_geom 覆盖 pts（物理坐标, N×3）则返回 True。"""
    d = np.array(img_geom["direction"]).reshape(3, 3)
    sp = np.array(img_geom["spacing"])
    o = np.array(img_geom["origin"])
    sz = np.array(img_geom["sizes"])
    idx = np.array([[x, y, z] for z in (0, sz[2] - 1)
                    for y in (0, sz[1] - 1) for x in (0, sz[0] - 1)], float)
    corners = o + (d @ (sp[:, None] * idx.T)).T
    mn, mx = corners.min(axis=0), corners.max(axis=0)
    return bool(np.all(pts >= mn - TOL) and np.all(pts <= mx + TOL))


def tumor_bbox_corners(mask_arr: np.ndarray, geom: dict) -> np.ndarray | None:
    """掩膜中肿瘤（标签1）包围盒的 8 个物理角点。"""
    zs, ys, xs = np.where(mask_arr == 1)
    if len(zs) == 0:
        return None
    idx = np.array([[x, y, z] for z in (zs.min(), zs.max())
                    for y in (ys.min(), ys.max())
                    for x in (xs.min(), xs.max())], float)
    d = np.array(geom["direction"]).reshape(3, 3)
    sp = np.array(geom["spacing"])
    o = np.array(geom["origin"])
    return o + (d @ (sp[:, None] * idx.T)).T


def save_qc(new_rows: list[dict]) -> None:
    rows = []
    if os.path.exists(QC_REPORT):
        try:
            rows = pd.read_csv(QC_REPORT, dtype=str).to_dict("records")
        except Exception:
            rows = []
    # The manifest stage is a complete rebuild.  Remove its previous records
    # so that a corrected source directory cannot leave stale FILE_COUNT or
    # geometry errors in the consolidated QC report.  Preserve QC records
    # generated by downstream stages.
    rows = [r for r in rows if str(r.get("阶段", "")) != "manifest"]
    rows.extend(new_rows)
    os.makedirs(os.path.dirname(QC_REPORT), exist_ok=True)
    pd.DataFrame(rows).to_csv(QC_REPORT, index=False, encoding="utf-8-sig")


def main() -> None:
    ap = argparse.ArgumentParser(description="构建数据清单 manifest.csv")
    ap.add_argument("--manifest", default=MANIFEST_CSV)
    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.manifest), exist_ok=True)

    ids = sorted(d for d in os.listdir(DIR_R1) if os.path.isdir(os.path.join(DIR_R1, d)))
    r2_ids = {d for d in os.listdir(DIR_R2) if os.path.isdir(os.path.join(DIR_R2, d))}
    rows: list[dict] = []
    qc_rows: list[dict] = []

    for pid in ids:
        d1 = os.path.join(DIR_R1, pid)
        img1, lbl1 = nrrd_files(d1)
        row = {"影像号": pid, "图像文件": "", "掩膜文件": "", "序列名": "",
               "尺寸": "", "层厚mm": "", "面内间距mm": "", "原点": "", "方向矩阵": "",
               "标签集合": "", "肿瘤体素": "", "肿瘤体积mm3": "", "肌肉体素": "",
               "脂肪体素": "", "几何一致": "1", "是否双读者": "0",
               "R2图像文件": "", "R2掩膜文件": "", "R2方向差异": "", "R2覆盖R1肿瘤": "",
               "R1标签2均灰度": "", "R1标签3均灰度": "", "R1标签3类别": "",
               "R2标签2均灰度": "", "R2标签3均灰度": "", "R2肌肉标签": "", "R2标签3类别": "",
               "R2肿瘤体素": "", "排除": "0", "排除原因": ""}
        if len(img1) != 1 or len(lbl1) != 1:
            qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "ERROR",
                            "代码": "FILE_COUNT", "说明": f"R1 图像{len(img1)}个/掩膜{len(lbl1)}个"})
            row.update({"排除": "1", "排除原因": "文件解析失败"})
            rows.append(row)
            continue
        row["图像文件"] = os.path.relpath(os.path.join(d1, img1[0]), ROOT)
        row["掩膜文件"] = os.path.relpath(os.path.join(d1, lbl1[0]), ROOT)
        row["序列名"] = os.path.splitext(img1[0])[0]
        i1 = sitk.ReadImage(os.path.join(d1, img1[0]))
        m1 = sitk.ReadImage(os.path.join(d1, lbl1[0]))
        g1 = geometry(i1)
        a1 = sitk.GetArrayFromImage(m1)
        cnt = np.bincount(a1.ravel(), minlength=4)
        tumor1, fat1, muscle1 = int(cnt[1]), int(cnt[2]), int(cnt[3])
        ai1 = sitk.GetArrayFromImage(i1)
        l2_1 = float(ai1[a1 == 2].mean()) if fat1 > 0 else float("nan")
        l3_1 = float(ai1[a1 == 3].mean()) if muscle1 > 0 else float("nan")
        if muscle1 > 0 and fat1 > 0:
            cls3_1 = "肌肉" if l3_1 < l2_1 else "脂肪"
        elif muscle1 > 0:
            cls3_1 = "肌肉（无标签2）"
        elif fat1 > 0:
            cls3_1 = "存疑（无标签3）"
        else:
            cls3_1 = "缺标签2/3"
        g_ok = g1["sizes"] == geometry(m1)["sizes"] and geom_diff(g1, geometry(m1)) <= TOL
        if not g_ok:
            qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "WARN",
                            "代码": "GEOM_MISMATCH", "说明": "图像与掩膜几何超出容差"})
        row.update({
            "尺寸": "x".join(map(str, g1["sizes"])),
            "层厚mm": f"{g1['spacing'][2]:.4f}",
            "面内间距mm": f"{g1['spacing'][0]:.4f}",
            "原点": " ".join(f"{x:.4f}" for x in g1["origin"]),
            "方向矩阵": " ".join(f"{x:.6f}" for x in g1["direction"]),
            "标签集合": "{" + ",".join(map(str, sorted(set(a1.ravel().tolist())))) + "}",
            "肿瘤体素": tumor1,
            "肿瘤体积mm3": round(tumor1 * float(np.prod(g1["spacing"])), 2),
            "肌肉体素": muscle1,
            "脂肪体素": fat1,
            "R1标签2均灰度": f"{l2_1:.2f}" if not math.isnan(l2_1) else "",
            "R1标签3均灰度": f"{l3_1:.2f}" if not math.isnan(l3_1) else "",
            "R1标签3类别": cls3_1,
            "几何一致": "1" if g_ok else "0",
        })
        if cls3_1 == "脂肪":
            qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "WARN",
                            "代码": "R1_LABEL3_NOT_MUSCLE",
                            "说明": "R1 标签3平均灰度高于标签2，非肌肉，请复核"})
        if tumor1 == 0:
            row.update({"排除": "1", "排除原因": "无肿瘤勾画"})
        elif tumor1 < MIN_TUMOR_VOXELS:
            row["排除原因"] = "肿瘤体素<10（记录评估）"

        if pid in r2_ids:
            row["是否双读者"] = "1"
            d2 = os.path.join(DIR_R2, pid)
            img2, lbl2 = nrrd_files(d2)
            if len(img2) != 1 or len(lbl2) != 1:
                qc_rows.append({"影像号": pid, "阶段": "manifest", "级别": "ERROR",
                                "代码": "FILE_COUNT", "说明": f"R2 图像{len(img2)}个/掩膜{len(lbl2)}个"})
            else:
                row["R2图像文件"] = os.path.relpath(os.path.join(d2, img2[0]), ROOT)
                row["R2掩膜文件"] = os.path.relpath(os.path.join(d2, lbl2[0]), ROOT)
                i2 = sitk.ReadImage(os.path.join(d2, img2[0]))
                m2 = sitk.ReadImage(os.path.join(d2, lbl2[0]))
                g2 = geometry(i2)
                a2 = sitk.GetArrayFromImage(m2)
                cnt2 = np.bincount(a2.ravel(), minlength=4)
                row["R2肿瘤体素"] = int(cnt2[1])
                row["R2方向差异"] = "1" if direction_diff(g1, g2) > TOL else "0"
                pts = tumor_bbox_corners(a1, g1)
                row["R2覆盖R1肿瘤"] = "1" if (pts is not None and fov_covers(g2, pts)) else "0"
                # R2 肌肉/脂肪判别：同图内标签2与标签3平均灰度，较低者为肌肉
                ai2 = sitk.GetArrayFromImage(i2)
                l2_2 = float(ai2[a2 == 2].mean()) if cnt2[2] > 0 else float("nan")
                l3_2 = float(ai2[a2 == 3].mean()) if cnt2[3] > 0 else float("nan")
                row["R2标签2均灰度"] = f"{l2_2:.2f}" if not math.isnan(l2_2) else ""
                row["R2标签3均灰度"] = f"{l3_2:.2f}" if not math.isnan(l3_2) else ""
                if not math.isnan(l2_2) and not math.isnan(l3_2):
                    row["R2肌肉标签"] = "2" if l2_2 < l3_2 else "3"
                    row["R2标签3类别"] = "肌肉" if l3_2 < l2_2 else "脂肪"
                elif not math.isnan(l3_2):
                    row["R2肌肉标签"] = "3"
                    row["R2标签3类别"] = "肌肉（无标签2）"
                elif not math.isnan(l2_2):
                    row["R2肌肉标签"] = "2"
                    row["R2标签3类别"] = "脂肪（无标签3）"
                else:
                    row["R2肌肉标签"] = "无"
                    row["R2标签3类别"] = "缺标签2/3"
        rows.append(row)

    df = pd.DataFrame(rows)
    df.to_csv(args.manifest, index=False, encoding="utf-8-sig")
    save_qc(qc_rows)

    roi = pd.read_excel(ROI_XLSX)
    col = "影像号" if "影像号" in roi.columns else roi.columns[0]
    roi_ids = set(str(x).strip() for x in roi[col])
    id_set = set(ids)
    n_excl = int((df["排除"] == "1").sum())
    n_small = int(df["排除原因"].str.contains("体素<10", na=False).sum())
    n_pair = int((df["是否双读者"] == "1").sum())
    d2 = df.loc[df["是否双读者"] == "1"]
    r2c = d2["R2标签3类别"].value_counts().to_dict()
    r2ml = d2["R2肌肉标签"].value_counts().to_dict()
    n_align = int((d2["R2方向差异"] == "1").sum())
    n_cover = int((d2["R2覆盖R1肿瘤"] == "1").sum())

    print(f"R1 病例数: {len(ids)} (result 内重复: {len(ids) - len(id_set)})")
    print(f"ROI_list 行数: {len(roi)}, 重复影像号: {int(roi[col].astype(str).str.strip().duplicated().sum())}, "
          f"与 result 交集: {len(id_set & roi_ids)}")
    print(f"ROI_list 有而 result 无: {sorted(roi_ids - id_set)[:10]}")
    print(f"result 有而 ROI_list 无: {sorted(id_set - roi_ids)[:10]}")
    print(f"排除(无肿瘤勾画): {n_excl}, 肿瘤<10体素(记录评估): {n_small}")
    print(f"双读者病例: {n_pair}, R2方向差异: {n_align}, R2覆盖R1肿瘤: {n_cover}")
    print(f"R2 标签3类别: {r2c}")
    print(f"R2 肌肉标签: {r2ml}")
    print(f"清单已写入: {args.manifest}")


if __name__ == "__main__":
    main()
